### ISSUE TITLE
Tier 1: Design Database Schema

### ISSUE THREAD

**Issue by jahedprince** [2211-Postman/grace-shopper#4]
Create models with these names:
-Users (Admin, customer)
-Products (Sneakers)
-Cart Items

Complete appropriate field names with types. Consider creating visual diagram.

**Comment by SNLTING** [comment]
https://lucid.app/lucidchart/b7857f21-026b-4c5a-8915-41758b19c26d/edit?viewport_loc=79%2C148%2C1672%2C1070%2C.tHmGxiUFhIP&invitationId=inv_a3d29119-71c1-4bbe-8092-5a1e14eb30c4
