### ISSUE TITLE
Tier 1: (BACKEND) Create GET Route for All Products/Users and Single Product/User

### ISSUE THREAD

**Issue by jahedprince** [2211-Postman/grace-shopper#6]
Create backend route for all products and single product in `server/api/products.js` 
Create backend route for all users and single user in `server/api/users.js`

**Comment by warrenchan13** [comment]
instead of creating a new branch for users routes, I accidentally committed and pushed the user routes changes to this ticket (originally products routes). Therefore, I just merged the two to this ticket
